

const LocalData = {
    AttendanceData : [
        {
            "_id": "66603b2ba3b307055fa8016c",
            "attendance_date": "2024-06-05",
            "emp_id": "emp115",
            "__v": 0,
            "attendance_month": "5",
            "attendance_stat": "",
            "attendance_year": "2024",
            "break_time": [
                {
                    "break_stime": "15:47:43",
                    "break_etime": "15:48:07",
                    "_id": "66603b60ddf47e060cf03000",
                    "total_break_time": "0.00"
                }
            ],
            "corporate_id": "ivn123",
            "created_at": "2024-06-05T10:17:15.592Z",
            "leave_type": "half_day",
            "login_by": "web",
            "register_type": "time",
            "status": "active",
            "updated_at": "2024-06-13T13:16:24.052Z",
            "login_out": "",
            "login_time": "15:47:14",
            "logout_time": "23:54",
            "total_logged_in": "8.6",
            "total_break_time": "0",
            "first_half": "P",
            "partial_apply_date": null,
            "partial_leave": null,
            "second_half": "P"
        },
        {
            "_id": "6662c7a6ac26ed74e418709b",
            "emp_id": "emp115",
            "attendance_date": "2024-06-06",
            "__v": 0,
            "attendance_month": "5",
            "attendance_stat": "",
            "attendance_year": "2024",
            "break_time": [],
            "corporate_id": "ivn123",
            "created_at": "2024-06-07T08:48:14.690Z",
            "created_by": "615336a2a69c86ed38a0dd65",
            "first_half": "P",
            "leave_type": "partial_day",
            "login_by": "web",
            "login_time": "10:15",
            "logout_time": "19:00",
            "partial_apply_date": "2024-06-06T00:00:00.000Z",
            "partial_leave": 250,
            "register_type": "time",
            "second_half": "P",
            "status": "active",
            "total_break_time": "0",
            "total_logged_in": "9",
            "updated_at": "2024-06-07T08:48:14.690Z"
        },
        {
            "_id": "666304ecac26ed74e4af7c9e",
            "attendance_date": "2024-06-07",
            "emp_id": "emp115",
            "__v": 0,
            "attendance_month": "5",
            "attendance_stat": "P",
            "attendance_year": "2024",
            "break_time": [
                {
                    "break_stime": "18:32:07",
                    "break_etime": "20:44:27",
                    "_id": "66632415b124dbf1a06d59de",
                    "total_break_time": "2.12"
                }
            ],
            "corporate_id": "ivn123",
            "created_at": "2024-06-07T13:02:36.389Z",
            "leave_type": "present",
            "login_by": "web",
            "register_type": "time",
            "status": "active",
            "updated_at": "2024-06-07T13:02:36.389Z",
            "login_out": "",
            "login_time": "18:32:07",
            "logout_time": "",
            "total_logged_in": "0.00",
            "total_break_time": "2.12"
        },
        {
            "_id": "6666a243ac26ed74e4b52066",
            "emp_id": "emp115",
            "attendance_date": "2024-06-01",
            "__v": 0,
            "attendance_month": "5",
            "attendance_stat": "",
            "attendance_year": "2024",
            "break_time": [],
            "corporate_id": "ivn123",
            "first_half": "P",
            "leave_type": "present",
            "login_by": "web",
            "login_time": "08:20",
            "logout_time": "20:20",
            "partial_apply_date": null,
            "partial_leave": null,
            "register_type": "time",
            "second_half": "P",
            "status": "active",
            "total_break_time": "1",
            "total_logged_in": "11.0",
            "updated_at": "2024-06-10T06:50:43.181Z"
        },
        {
            "_id": "66693190ac26ed74e492218c",
            "attendance_date": "2024-06-04",
            "emp_id": "emp115",
            "__v": 0,
            "attendance_month": "5",
            "attendance_stat": "WO",
            "attendance_year": "2024",
            "break_time": [],
            "corporate_id": "ivn123",
            "first_half": "WO",
            "leave_type": "full_day",
            "login_by": "web",
            "login_time": "10:00",
            "logout_time": "19:00",
            "partial_apply_date": null,
            "partial_leave": null,
            "register_type": "time",
            "second_half": "WO",
            "status": "active",
            "total_break_time": "1",
            "total_logged_in": "8.0",
            "updated_at": "2024-06-13T06:50:43.960Z"
        },
        {
            "_id": "666a96c4ac26ed74e4b7515b",
            "attendance_date": "2024-06-11",
            "emp_id": "emp115",
            "__v": 0,
            "attendance_stat": "H",
            "break_time": [],
            "corporate_id": "ivn123",
            "first_half": "H",
            "leave_type": "full_day",
            "second_half": "H",
            "updated_at": "2024-06-13T12:20:08.659Z",
            "attendance_month": "5",
            "attendance_year": "2024",
            "login_by": "web",
            "login_time": "10:00",
            "logout_time": "19:00",
            "partial_apply_date": null,
            "partial_leave": null,
            "register_type": "time",
            "status": "active",
            "total_break_time": "1",
            "total_logged_in": "8.0"
        },
        {
            "_id": "666aca03ac26ed74e4659cfe",
            "emp_id": "emp115",
            "attendance_date": "2024-06-13",
            "__v": 0,
            "attendance_month": "5",
            "attendance_stat": "CSL",
            "attendance_year": "2024",
            "break_time": [
                {
                    "break_stime": "15:59:26",
                    "break_etime": "15:59:30",
                    "_id": "666aca0d6c4bf254c26b422d",
                    "total_break_time": "0.00"
                }
            ],
            "corporate_id": "ivn123",
            "created_at": "2024-06-13T10:29:23.173Z",
            "leave_type": "full_day",
            "login_by": "web",
            "register_type": "time",
            "status": "active",
            "updated_at": "2024-06-13T13:17:35.256Z",
            "login_out": "",
            "login_time": "15:59:20",
            "logout_time": "17:07:28",
            "total_logged_in": "-1.-52",
            "total_break_time": "2",
            "first_half": "CSL",
            "partial_apply_date": null,
            "partial_leave": null,
            "second_half": "CSL"
        },
        {
            "_id": "666c373dac26ed74e4f5ea20",
            "attendance_date": "2024-06-14",
            "emp_id": "emp115",
            "__v": 0,
            "attendance_month": "5",
            "attendance_stat": "P",
            "attendance_year": "2024",
            "break_time": [],
            "corporate_id": "ivn123",
            "created_at": "2024-06-14T12:27:41.049Z",
            "leave_type": "present",
            "login_by": "web",
            "register_type": "time",
            "status": "active",
            "updated_at": "2024-06-14T12:27:41.049Z",
            "login_out": "",
            "login_time": "17:57:40",
            "logout_time": "17:59:42",
            "total_logged_in": "0.02"
        },
        {
            "_id": "667421b2ac26ed74e400f233",
            "attendance_date": "2024-06-20",
            "emp_id": "emp115",
            "__v": 0,
            "attendance_month": "5",
            "attendance_stat": "P",
            "attendance_year": "2024",
            "break_time": [
                {
                    "break_stime": "18:37:24",
                    "break_etime": "18:41:30",
                    "_id": "66742cd870790e05d868b95d",
                    "total_break_time": "0.04"
                }
            ],
            "corporate_id": "ivn123",
            "created_at": "2024-06-20T12:33:53.893Z",
            "first_half": "P",
            "leave_type": "present",
            "login_by": "web",
            "register_type": "time",
            "second_half": "P",
            "status": "active",
            "updated_at": "2024-06-20T12:33:53.893Z",
            "login_out": "",
            "login_time": "18:03:41",
            "logout_time": "18:41:30",
            "total_logged_in": "0.33",
            "total_break_time": "0.04"
        }
    ]
};

export default LocalData;
